export interface Listing {
    id: number;
    country_code: string;
    user_id: number;
    category_id: number;
    post_type_id: number;
    title: string;
    description: string;
    tags: string[];
    price: string;
    negotiable: number;
    contact_name: string;
    auth_field: string;
    email: string;
    phone: string;
    phone_national: string;
    phone_country: string;
    phone_hidden: number;
    address: string | null;
    city_id: number;
    lat: number;
    lon: number;
    ip_addr: string;
    visits: number;
    tmp_token: string;
    email_token: string | null;
    phone_token: string | null;
    email_verified_at: string | null;
    phone_verified_at: string | null;
    accept_terms: number;
    accept_marketing_offers: number;
    is_permanent: number;
    reviewed_at: string | null;
    featured: number;
    archived_at: string | null;
    archived_manually_at: string | null;
    deletion_mail_sent_at: string | null;
    fb_profile: string | null;
    partner: string | null;
    created_at: string;
    updated_at: string;
    slug: string;
    url: string;
    phone_intl: string;
    created_at_formatted: string;
    user_photo_url: string;
    country_flag_url: string;
    price_label: string;
    price_formatted: string;
    count_pictures: number;
    picture: {
        filename: string;
        url: {
            full: string;
            small: string;
            medium: string;
            big: string;
        };
    };
    pictures: {
        active: number;
        filename: string;
        id: number;
        mime_type: string;
        position: number;
        url: {
            full: string;
            small: string;
            medium: string;
            big: string;
        };
    };
}
